### ISSUE TITLE
Nethunter awus036ac RTL8812AU 

### ISSUE THREAD

**Issue by axeldog** [yesimxev/nethunter_files#2]
Please help as you can see cannot install RTL8812AU driver even thought it says in nethunter docs it is a supported chipset. 
![20231027_003754](https://github.com/yesimxev/nethunter_files/assets/147840569/9f83dded-fd62-4290-a6fc-091692567147)

**Comment by yesimxev** [comment]
Please check this video, you can reproduce without doing all the NH stuff, just skip to where I add that driver (at 5.13) https://www.youtube.com/watch?v=FwSHbZqY88k

**Comment by axeldog** [comment]
How can I uninstall nethunter without loosing root and having to factory reset every time.

**Comment by yesimxev** [comment]
[uninstaller-nethunter-20231031_104212.zip](https://github.com/yesimxev/nethunter_files/files/13215264/uninstaller-nethunter-20231031_104212.zip)

**Comment by axeldog** [comment]
Which method do I use to flash the zip. Franco kernel manager or twrp. Is that universal uninstaller or phone modle specific. Also dose it totally remove nethunter or just the kernel made in the nethunter project?

**Comment by yesimxev** [comment]
TWRP. It remove everything, except the kernel. You have to flash stock kernel back if you need to. Is it an already supported device so it has NH kernel?

**Comment by axeldog** [comment]
so i have nh on my oneplu7t rooted and as you can tell im having problems with the awus036ac wifi adaptor rtl8812au driver iv chated with ZerBea and he pointed out the difference with the kernel and API so i factory reset my phone and installd a different stock version and re rooted installe nethunter image then a nh kernel from nh installer project same thing happend ended up on cyberknight777 -1.0 4.14.234 . on the nh installer project i used the build py comand -d oneplus7-all -R -k is that where the cyberknight comes from?

**Comment by yesimxev** [comment]
I think so but it has that driver. Show me dmesg after you plug in

**Comment by axeldog** [comment]
already reset phone going to install the other oneplus nh image.

**Comment by axeldog** [comment]
iv downloaded the [OnePlus 7 / 7 Pro / 7T / 7T Pro (OxygenOS/Custom A11)nh img installed it with magisk module. what build.py command would you suggest that would work best
-d oneplus7-oos -R -fs full
-d oneplus7-oos -R
 -d oneplus7-oos -R -k

**Comment by axeldog** [comment]
checked about phone befor installing the kernel and cyberknight777 4.14.234 is alresdy there

**Comment by axeldog** [comment]
on the previous build i used [OnePlus 7 / 7 Pro / 7T / 7T Pro (Eleven) nethunter img. both have the cyberknight777 kernel.

**Comment by yesimxev** [comment]
I'm not sure but both ten and eleven kernels have rtl88xxau (rtl8812/8814au) support. See https://nethunter.kali.org/kernels.html

You should do `dmesg -c` plug in adapter, then `dmesg` again. Show me a screenshot after the second dmesg

**Comment by axeldog** [comment]
![Screenshot_20231031-224537](https://github.com/yesimxev/nethunter_files/assets/147840569/419591bd-9889-4a4f-b450-9dce5c35dbfe)
![Screenshot_20231031-224649](https://github.com/yesimxev/nethunter_files/assets/147840569/892cb74c-6ad6-4c16-a3db-24fbda6c8609)

**Comment by yesimxev** [comment]
apt-get install firmware-realtek

**Comment by axeldog** [comment]
Didn't work.

**Comment by yesimxev** [comment]
There may be not enough power through your OTG adapter. Can you try another one? Example I had one where it only worked about every 10th plug in. You can also try oos-10, that kernel has internal bluetooth support too

**Comment by axeldog** [comment]
My tplink adaptor works no problem plug and play.
